name: Test SFTP Connection and Upload

on:
  workflow_dispatch: # Trigger workflow manually

jobs:
  upload-to-sftp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Upload files to GoDaddy via SFTP
      uses: appleboy/scp-action@v0.1.7
      with:
        host: "fcltdbd.com"
        username: "cpy77mtp6og4"
        passphrase: "mbm123"
        privateKey: ${{ vars.sftp }}
        port: 22
        local: "./erp/.env.local"
        target: "/home/cpy77mtp6og4/public_html/erpreport.fcltdbd.com/testOut/.env.local"
