name: Test SFTP Connection and Upload

on:
  workflow_dispatch: # Trigger workflow manually

jobs:
  upload-to-sftp:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Upload files to GoDaddy via SFTP
      uses: garygrossgarten/github-action-scp@release
      with:
        host: "fcltdbd.com"
        username: "cpy77mtp6og4"
        passphrase: "mbm123"
        privateKey: ${{ vars.sftp }}
        port: 22
        local: "./erp/out"
        remote: "/home/cpy77mtp6og4/public_html/erpreport.fcltdbd.com/testOut"
